export interface Riddle {
  id: number;
  question: string;
  options: string[];
  answer: string;
}

export const techRiddles: Riddle[] = [
  { id: 1, question: "I have a brain but no consciousness, I can learn but cannot feel. What am I?", options: ["Artificial Intelligence", "Processor", "Server", "Database"], answer: "Artificial Intelligence" },
  { id: 2, question: "I have keys but no locks. I have space but no room. You can enter but not go outside. What am I?", options: ["Keyboard", "Hard Drive", "Network", "Server Room"], answer: "Keyboard" },
  { id: 3, question: "I connect the world but have no voice. I am invisible but everywhere. What am I?", options: ["The Internet", "Bluetooth", "A Router", "Fiber Optic"], answer: "The Internet" },
  { id: 4, question: "I hold your memories, but I have no mind. I come in gigabytes and terabytes. What am I?", options: ["Hard Drive", "RAM", "CPU", "Motherboard"], answer: "Hard Drive" },
  { id: 5, question: "I remember everything until you turn me off, then I forget it all. What am I?", options: ["RAM", "ROM", "Cache", "SSD"], answer: "RAM" },
  { id: 6, question: "I have a heart of silicon and beat in gigahertz. What am I?", options: ["CPU", "GPU", "Power Supply", "Motherboard"], answer: "CPU" },
  { id: 7, question: "I catch bugs but I am not a spider. I am a process, not a physical thing. What am I?", options: ["Debugger", "Compiler", "Antivirus", "Firewall"], answer: "Debugger" },
  { id: 8, question: "I am a wall that blocks bad traffic but lets the good through. What am I?", options: ["Firewall", "Router", "Switch", "VPN"], answer: "Firewall" },
  { id: 9, question: "I translate human text into machine language. What am I?", options: ["Compiler", "Database", "Operating System", "IDE"], answer: "Compiler" },
  { id: 10, question: "I organize data into tables and relations. What am I?", options: ["Relational Database", "Hard Drive", "Spreadsheet", "Cloud Storage"], answer: "Relational Database" },
  { id: 11, question: "I wrap your internet traffic in a secure tunnel. What am I?", options: ["VPN", "Proxy", "Firewall", "Router"], answer: "VPN" },
  { id: 12, question: "I point at things but have no fingers. I double-click but have no mouth. What am I?", options: ["Mouse", "Cursor", "Touchpad", "Stylus"], answer: "Mouse" },
  { id: 13, question: "I am composed of 1s and 0s. What am I?", options: ["Binary Code", "Hexadecimal", "ASCII", "Assembly"], answer: "Binary Code" },
  { id: 14, question: "I resolve names to numbers so you don't have to remember IPs. What am I?", options: ["DNS", "DHCP", "FTP", "HTTP"], answer: "DNS" },
  { id: 15, question: "I assign IP addresses dynamically on a network. What am I?", options: ["DHCP", "DNS", "Gateway", "Subnet Mask"], answer: "DHCP" },
  { id: 16, question: "I live in the cloud but precipitation doesn't affect me. What am I?", options: ["SaaS", "Umbrella", "Rain", "Fog Network"], answer: "SaaS" },
  { id: 17, question: "I store secrets securely, turning readable things unreadable. What am I?", options: ["Encryption", "Compression", "Hashing", "Obfuscation"], answer: "Encryption" },
  { id: 18, question: "I take multiple files and squeeze them into one smaller package. What am I?", options: ["Compression (ZIP)", "Encryption", "Compiler", "Assembler"], answer: "Compression (ZIP)" },
  { id: 19, question: "I provide an environment to write, run, and debug code. What am I?", options: ["IDE", "API", "SDK", "CLI"], answer: "IDE" },
  { id: 20, question: "I am a contract between software components. What am I?", options: ["API", "SDK", "Library", "Framework"], answer: "API" },
  { id: 21, question: "I am a malicious self-replicating program. What am I?", options: ["Worm", "Trojan", "Spyware", "Adware"], answer: "Worm" },
  { id: 22, question: "I pretend to be useful software but secretly harm your computer. What am I?", options: ["Trojan", "Worm", "Keylogger", "Ransomware"], answer: "Trojan" },
  { id: 23, question: "I lock your files and demand payment for the key. What am I?", options: ["Ransomware", "Adware", "Spyware", "Trojan"], answer: "Ransomware" },
  { id: 24, question: "I am the main circuit board that connects all hardware components. What am I?", options: ["Motherboard", "CPU", "GPU", "Power Supply"], answer: "Motherboard" },
  { id: 25, question: "I make games look realistic and process massive matrices for AI. What am I?", options: ["GPU", "CPU", "RAM", "APU"], answer: "GPU" },
  { id: 26, question: "I am a physical piece of tech you strap to your face for a different reality. What am I?", options: ["VR Headset", "Smart Glasses", "Monitor", "Webcam"], answer: "VR Headset" },
  { id: 27, question: "I distribute incoming traffic across multiple servers. What am I?", options: ["Load Balancer", "Reverse Proxy", "Gateway", "Router"], answer: "Load Balancer" },
  { id: 28, question: "I sit between the client and the internet, fetching resources on their behalf. What am I?", options: ["Forward Proxy", "Load Balancer", "Firewall", "DNS"], answer: "Forward Proxy" },
  { id: 29, question: "I am an immutable ledger of transactions distributed across nodes. What am I?", options: ["Blockchain", "Database", "Log File", "Cache"], answer: "Blockchain" },
  { id: 30, question: "I store temporary data to serve future requests faster. What am I?", options: ["Cache", "ROM", "Hard Drive", "Database"], answer: "Cache" },
  { id: 31, question: "I am an error, flaw, or fault in a computer program or system. What am I?", options: ["Bug", "Feature", "Patch", "Update"], answer: "Bug" },
  { id: 32, question: "I am a sequence of instructions telling a computer what to do. What am I?", options: ["Algorithm", "Variable", "Loop", "Syntax"], answer: "Algorithm" },
  { id: 33, question: "I allow multiple operating systems to run on a single physical machine. What am I?", options: ["Hypervisor", "Container", "Emulator", "Simulator"], answer: "Hypervisor" },
  { id: 34, question: "I package code and its dependencies so it runs reliably anywhere. What am I?", options: ["Container (e.g., Docker)", "Virtual Machine", "Repository", "Package Manager"], answer: "Container (e.g., Docker)" },
  { id: 35, question: "I manage source code history and track changes over time. What am I?", options: ["Version Control (Git)", "Backup System", "File Explorer", "Log Manager"], answer: "Version Control (Git)" },
  { id: 36, question: "I am the language that styles the web. What am I?", options: ["CSS", "HTML", "JavaScript", "PHP"], answer: "CSS" },
  { id: 37, question: "I am the bone structure of a webpage. What am I?", options: ["HTML", "CSS", "SQL", "Python"], answer: "HTML" },
  { id: 38, question: "I bring interactivity and behavior to webpages. What am I?", options: ["JavaScript", "HTML", "CSS", "XML"], answer: "JavaScript" },
  { id: 39, question: "I query structured databases. What am I?", options: ["SQL", "NoSQL", "JSON", "XML"], answer: "SQL" },
  { id: 40, question: "I am a lightweight data-interchange format, easy for humans and machines. What am I?", options: ["JSON", "XML", "YAML", "CSV"], answer: "JSON" },
  { id: 41, question: "I automate the building, testing, and deployment of code. What am I?", options: ["CI/CD Pipeline", "IDE", "Version Control", "Compiler"], answer: "CI/CD Pipeline" },
  { id: 42, question: "I try to trick you into revealing your passwords via fake emails. What am I?", options: ["Phishing", "Spoofing", "DDoS", "Malware"], answer: "Phishing" },
  { id: 43, question: "I flood a server with traffic until it crashes. What am I?", options: ["DDoS Attack", "SQL Injection", "XSS", "Brute Force"], answer: "DDoS Attack" },
  { id: 44, question: "I guess all possible password combinations until I get in. What am I?", options: ["Brute Force Attack", "Social Engineering", "Man in the middle", "Zero-day"], answer: "Brute Force Attack" },
  { id: 45, question: "I exploit a vulnerability before the vendor even knows about it. What am I?", options: ["Zero-day Exploit", "Patch", "Backdoor", "Trojan"], answer: "Zero-day Exploit" },
  { id: 46, question: "I am a widely used open-source operating system kernel. What am I?", options: ["Linux", "Windows", "macOS", "DOS"], answer: "Linux" },
  { id: 47, question: "I am a command-line interface that executes commands in Unix-like systems. What am I?", options: ["Shell / Bash", "GUI", "IDE", "Compiler"], answer: "Shell / Bash" },
  { id: 48, question: "I resolve MAC addresses to IP addresses. What am I?", options: ["ARP", "DNS", "DHCP", "NAT"], answer: "ARP" },
  { id: 49, question: "I hide internal IPs behind a single public IP. What am I?", options: ["NAT", "VPN", "Proxy", "Firewall"], answer: "NAT" },
  { id: 50, question: "I ensure data isn't altered during transmission. What am I?", options: ["Integrity (Hashing)", "Confidentiality", "Availability", "Authentication"], answer: "Integrity (Hashing)" },
  { id: 51, question: "I am the practice of hiding a secret message within an ordinary file. What am I?", options: ["Steganography", "Cryptography", "Obfuscation", "Encoding"], answer: "Steganography" },
  { id: 52, question: "I verify your identity, proving you are who you say you are. What am I?", options: ["Authentication", "Authorization", "Accounting", "Auditing"], answer: "Authentication" },
  { id: 53, question: "I determine what you are allowed to do after logging in. What am I?", options: ["Authorization", "Authentication", "Accounting", "Identification"], answer: "Authorization" },
  { id: 54, question: "I am a design pattern that separates application, business logc, and UI. What am I?", options: ["MVC", "Singleton", "Factory", "Observer"], answer: "MVC" },
  { id: 55, question: "I ensure only one instance of a class is created. What am I?", options: ["Singleton Pattern", "Factory Pattern", "Builder Pattern", "Prototype"], answer: "Singleton Pattern" },
  { id: 56, question: "I am a network of physical objects embedded with sensors and software. What am I?", options: ["IoT", "Cloud", "Edge Computing", "Quantum Computing"], answer: "IoT" },
  { id: 57, question: "I am meant to determine if a machine can exhibit human-like intelligence. What am I?", options: ["Turing Test", "CAPTCHA", "Stress Test", "Unit Test"], answer: "Turing Test" },
  { id: 58, question: "I tell humans and bots apart using squiggly letters or streetlights. What am I?", options: ["CAPTCHA", "MFA", "Biometrics", "Password"], answer: "CAPTCHA" },
  { id: 59, question: "I require more than just a password to grant access. What am I?", options: ["Multi-Factor Authentication", "SSO", "OAuth", "LDAP"], answer: "Multi-Factor Authentication" },
  { id: 60, question: "I am a methodology that emphasizes iterative software development. What am I?", options: ["Agile", "Waterfall", "V-Model", "Spiral"], answer: "Agile" },
  { id: 61, question: "I run code very close to the data source rather than in a centralized cloud. What am I?", options: ["Edge Computing", "Mainframe", "Grid Computing", "Serverless"], answer: "Edge Computing" },
  { id: 62, question: "I allow you to spin up code fragments without managing the underlying server. What am I?", options: ["Serverless computing", "IaaS", "PaaS", "Bare Metal"], answer: "Serverless computing" },
  { id: 63, question: "I am a JavaScript library for building user interfaces, characterized by my virtual DOM. What am I?", options: ["React", "Angular", "Vue", "Svelte"], answer: "React" },
  { id: 64, question: "I allow you to run JavaScript on the server side, built on Chrome's V8 engine. What am I?", options: ["Node.js", "Django", "Deno", "Ruby on Rails"], answer: "Node.js" },
  { id: 65, question: "I am a Greek word for helmsman, but in tech, I orchestrate containers. What am I?", options: ["Kubernetes", "Docker Swarm", "Mesos", "Terraform"], answer: "Kubernetes" },
  { id: 66, question: "I am a method of software architecture where complex applications are broken down into small, independent processes. What am I?", options: ["Microservices", "Monolith", "SOA", "MVC"], answer: "Microservices" },
  { id: 67, question: "I am the hidden part of the internet, unindexed by standard search engines. What am I?", options: ["Dark Web", "Deep Web", "Intranet", "Extranet"], answer: "Dark Web" },
  { id: 68, question: "I am code that is freely available to be modified and shared by anyone. What am I?", options: ["Open Source", "Freeware", "Shareware", "Proprietary"], answer: "Open Source" },
  { id: 69, question: "I manage APIs, route requests, and enforce security policies. What am I?", options: ["API Gateway", "Load Balancer", "Reverse Proxy", "Firewall"], answer: "API Gateway" },
  { id: 70, question: "I am a high-level programming language named after a British comedy troupe, not a snake. What am I?", options: ["Python", "Ruby", "Lua", "Perl"], answer: "Python" },
  { id: 71, question: "I process vast amounts of data beyond the capabilities of traditional databases. What am I?", options: ["Big Data", "Data Lake", "Data Warehouse", "Relational Database"], answer: "Big Data" },
  { id: 72, question: "I am a machine that uses the principles of quantum mechanics to process information exponentially faster. What am I?", options: ["Quantum Computer", "Supercomputer", "Mainframe", "Server Cluster"], answer: "Quantum Computer" },
  { id: 73, question: "I mimic the human brain to solve complex problems through interconnected nodes. What am I?", options: ["Neural Network", "Decision Tree", "Support Vector Machine", "Random Forest"], answer: "Neural Network" },
  { id: 74, question: "I allow computers to learn from data without being explicitly programmed. What am I?", options: ["Machine Learning", "Data Mining", "Data Science", "Algorithm"], answer: "Machine Learning" },
  { id: 75, question: "I use flexible, time-boxed iterations called sprints to manage software projects. What am I?", options: ["Scrum", "Kanban", "Waterfall", "Six Sigma"], answer: "Scrum" },
  { id: 76, question: "I am a lightweight markup language with plain-text-formatting syntax. What am I?", options: ["Markdown", "HTML", "XML", "Rich Text Format"], answer: "Markdown" },
  { id: 77, question: "I am the fifth generation of mobile network technology, promising ultra-low latency. What am I?", options: ["5G", "LTE", "Wi-Fi 6", "Starlink"], answer: "5G" },
  { id: 78, question: "I am the internet protocol designed to replace IPv4 due to address exhaustion. What am I?", options: ["IPv6", "IPv5", "TCP", "UDP"], answer: "IPv6" },
  { id: 79, question: "I transmit data at the speed of light through glass or plastic threads. What am I?", options: ["Fiber Optic", "Coaxial Cable", "Ethernet", "Twisted Pair"], answer: "Fiber Optic" },
  { id: 80, question: "I am a virtual representation of a physical object, process, or system. What am I?", options: ["Digital Twin", "Simulacrum", "Avatar", "Hologram"], answer: "Digital Twin" },
  { id: 81, question: "I am the practice of using remote servers on the internet to store, manage, and process data. What am I?", options: ["Cloud Computing", "Grid Computing", "Edge Computing", "On-Premise"], answer: "Cloud Computing" },
  { id: 82, question: "I am an object-oriented language developed by Bjarne Stroustrup as an extension of C. What am I?", options: ["C++", "C#", "Objective-C", "Java"], answer: "C++" }
];
